# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-12-13 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slice_type', models.CharField(default=None, max_length=255, null=True)),
                ('slice_position', models.FloatField(default=None)),
            ],
        ),
    ]
